# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
    name='image.proto',
    package='com.criteo.hadoop.recocomputer.jobs.imagedl',
    serialized_pb='\n\x0bimage.proto\x12+com.criteo.hadoop.recocomputer.jobs.imagedl\"\xf0\x01\n\x0cProductImage\x12\x12\n\npartner_id\x18\x01 \x02(\x05\x12\x13\n\x0binternal_id\x18\x02 \x02(\x05\x12\x18\n\x10\x65xternal_item_id\x18\x03 \x02(\t\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\x11\n\timage_md5\x18\x05 \x01(\x05\x12\r\n\x05image\x18\x06 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x07 \x01(\t\x12R\n\x0eimage_features\x18\x08 \x01(\x0b\x32:.com.criteo.hadoop.recocomputer.jobs.imagedl.ImageFeatures\"Y\n\rImageFeatures\x12\x14\n\x0c\x61spect_ratio\x18\x01 \x01(\x02\x12\x17\n\x0bhog_weights\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x19\n\rrgb_histogram\x18\x03 \x03(\x05\x42\x02\x10\x01')


_PRODUCTIMAGE = _descriptor.Descriptor(
    name='ProductImage',
    full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='partner_id', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage.partner_id', index=0,
            number=1, type=5, cpp_type=1, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='internal_id', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage.internal_id', index=1,
            number=2, type=5, cpp_type=1, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='external_item_id', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage.external_item_id', index=2,
            number=3, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='image_url', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage.image_url', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='image_md5', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage.image_md5', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='image', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage.image', index=5,
            number=6, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='image_format', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage.image_format', index=6,
            number=7, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='image_features', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage.image_features', index=7,
            number=8, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=61,
    serialized_end=301,
)


_IMAGEFEATURES = _descriptor.Descriptor(
    name='ImageFeatures',
    full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ImageFeatures',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='aspect_ratio', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ImageFeatures.aspect_ratio', index=0,
            number=1, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='hog_weights', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ImageFeatures.hog_weights', index=1,
            number=2, type=2, cpp_type=6, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
        _descriptor.FieldDescriptor(
            name='rgb_histogram', full_name='com.criteo.hadoop.recocomputer.jobs.imagedl.ImageFeatures.rgb_histogram', index=2,
            number=3, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=303,
    serialized_end=392,
)

_PRODUCTIMAGE.fields_by_name['image_features'].message_type = _IMAGEFEATURES
DESCRIPTOR.message_types_by_name['ProductImage'] = _PRODUCTIMAGE
DESCRIPTOR.message_types_by_name['ImageFeatures'] = _IMAGEFEATURES


class ProductImage(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PRODUCTIMAGE

    # @@protoc_insertion_point(class_scope:com.criteo.hadoop.recocomputer.jobs.imagedl.ProductImage)


class ImageFeatures(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _IMAGEFEATURES

    # @@protoc_insertion_point(class_scope:com.criteo.hadoop.recocomputer.jobs.imagedl.ImageFeatures)


_IMAGEFEATURES.fields_by_name['hog_weights'].has_options = True
_IMAGEFEATURES.fields_by_name['hog_weights']._options = _descriptor._ParseOptions(
    descriptor_pb2.FieldOptions(), '\020\001')
_IMAGEFEATURES.fields_by_name['rgb_histogram'].has_options = True
_IMAGEFEATURES.fields_by_name['rgb_histogram']._options = _descriptor._ParseOptions(
    descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
